version: '3.8'
services:
  db:
    container_name: db-learnweb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '${PHPADMIN_PORT}:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db
